name: Build APK
on: [push]
jobs:
  buildozer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: master
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tu-Pronosticos-APK
          path: ./bin/*.apk
